title: Joshua G. Medina
logo: assets/img/pic.jpg
description: Current main focused on the assembly of a high-quality genome of the sea cucumber <i>Holothuria glaberrima</i> and scRNA-seq of its regenerating intestinal tissue.
#show_downloads: false
theme: jekyll-theme-minimal